spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com